theme: jekyll-theme-cayman
title: Cisco UCS Monitoring Extension 
description: AppDynamics Monitoring Solution for Cisco UCS
show_downloads: true

github:
  mac_url: https://github.com/Appdynamics/ucs-monitoring-extension-ps1/releases/tag/v1.0
